# The default configuration used by the Clace server and client

server_uri = "$CL_HOME/run/clace.sock" # the unix domain socket (UDS) path or URL to the Clace server
admin_user = "admin"

# Properties use by the Clace client to connect to the server
[client]
admin_password = ""      # the password for the admin user. Required only if admin over TCP is enabled
skip_cert_check = false
default_format = "table" # default output format for the client commands

# HTTP port binding related Config
[http]
host = "127.0.0.1" # bind to localhost by default for HTTP
port = 25222       # default port for HTTP

# HTTPS port binding related Config
[https]
host = "0.0.0.0"                               # bind to all interfaces (if port is >= 0)
port = 25223                                   # port for HTTPS
enable_cert_lookup = true                      # enable looking for certificate files on disk before using Let's Encrypt
service_email = ""                             # email address for registering with Let's Encrypt. Set a value to enable automatic certs
use_staging = true                             # use Let's Encrypt staging server
cert_location = "$CL_HOME/config/certificates" # where to look for existing certificate files
storage_location = "$CL_HOME/run/certmagic"    # where to cache dynamically created certificates

[security]
admin_over_tcp = false           # enable admin API's over TCP (HTTP/HTTPS). Admin is over UDS only by default
admin_password_bcrypt = ""       # the password bcrypt value
app_default_auth_type = "system" # default auth type for new apps, "system" or "none" or custom auth
session_secret = ""              # the secret key for session cookie. Auto generated on server startup if not set
session_max_age = 86400          # session max age in seconds
session_https_only = true        # session cookie is HTTPS only

# Logging related Config
[logging]
level = "INFO"
max_backups = 10
max_size_mb = 50
console = false
file = true
access_logging = true

# Metadata Storage Config
[metadata]
db_connection = "sqlite:$CL_HOME/clace.db"
auto_upgrade = true

[system]
tailwindcss_command = "tailwindcss"
file_watcher_debounce_millis = 300
node_path = ""                      # node module lookup paths https://esbuild.github.io/api/#node-paths
container_command = "auto"          # "auto" or "docker" or "podman"

[plugin."store.in"]
db_connection = "sqlite:$CL_HOME/clace_app.db"

[app_config]
# app config can be set at the app level using a metadata config update. For example:
#  clace app update-metadata conf --promote cors.allow_methods="GET, POST" /myapp

# ==== CORS related Config ====
# Default setting is to add CORS headers with * as allow_origin header. If cors.allow_origin is set to empty string,
# no CORS headers are set. If allow_origin is set to "origin", the origin host is used as the allow_origin header. 
# For any other value for cors.allow_origin, the specified value is used as the allow_origin header.
cors.allow_origin = "*"
cors.allow_methods = "*"
cors.allow_headers = "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,X-Requested-With"
cors.allow_credentials = "true"
cors.max_age = "2678400"                                                                                                                 # 31 days

# ==== Container related Config ====

# Health check Config
container.health_url = "/"
container.health_attempts_after_startup = 30
container.health_timeout_secs = 5

# Idle Shutdown Config
container.idle_shutdown_secs = 180
container.idle_shutdown_dev_apps = false

# Status check Config
container.status_check_interval_secs = 5
container.status_health_attempts = 3

# Proxy related settings
proxy.max_idle_conns = 250
proxy.idle_conn_timeout_secs = 15
proxy.disable_compression = true
