project_name: clace

builds:
  - main: ./cmd/clace
    id: clace
    binary: clace
    ldflags:
      - -w -X github.com/claceio/clace/server.gitCommit={{.ShortCommit}}
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256

snapshot:
  name_template: '{{ if index .Env "IMAGE_NAME"  }}{{ .Env.IMAGE_NAME }}{{ else if not (eq .Branch "main" "dev" "") }}{{ replace .Branch "/" "-" }}{{ else }}nightly{{ end }}-{{ time "20060102" }}'
