project_name: clace

release:
  github:
    owner: claceio
    name: clace
  name_template: "Release {{.Tag}}"
  draft: true

changelog:
  skip: true

before:
  hooks:
    - go mod download
    - go mod tidy
    - go test -race ./...

builds:
  - main: ./cmd/clace
    binary: clace
    flags:
      - -trimpath
    ldflags:
      - -w -X github.com/claceio/clace/server.gitCommit={{.ShortCommit}}
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

nfpms:
  - file_name_template: "{{.ProjectName}}-{{.Tag}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}"
    homepage: https://clace.io/
    description: Securely develop and deploy internal applications
    maintainer: Ajay Kidave <contact@clace.io>
    license: Apache 2.0
    vendor: ClaceIO LLC.
    formats:
      - deb
      - rpm
    contents:
      - src: /usr/bin/clace
        dst: /usr/local/bin/clace
        type: "symlink"

archives:
  - name_template: "{{.ProjectName}}-{{.Tag}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}"
    wrap_in_directory: true
    format: zip
    files:
      - README.md
      - LICENSE
  - name_template: "{{.ProjectName}}-{{.Tag}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}"
    id: targz-archives
    wrap_in_directory: true
    format: tar.gz
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256
