project_name: clace

release:
  github:
    owner: claceio
    name: clace
  name_template: "Release {{.Tag}}"
  draft: true
  prerelease: "true"

before:
  hooks:
    - go mod download
    - go mod tidy
    - go test -race ./...

builds:
  - main: ./cmd/clace
    binary: clace
    flags:
      - -trimpath
    ldflags:
      - -w
      - -X github.com/claceio/clace/version.GitCommit={{.ShortCommit}}
      - -X github.com/claceio/clace/version.BuildDate={{.Date}}
      - -X github.com/claceio/clace/version={{.Version}}
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

nfpms:
  - file_name_template: "{{.ProjectName}}-{{.Tag}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}"
    homepage: https://clace.io/
    description: Securely develop and deploy internal applications
    maintainer: Ajay Kidave <contact@clace.io>
    license: Apache 2.0
    vendor: ClaceIO LLC.
    formats:
      - deb
      - rpm
    contents:
      - src: /usr/bin/clace
        dst: /usr/local/bin/clace
        type: "symlink"

checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256

archives:
  - id: windows
    name_template: >-
      {{ .ProjectName }}_{{ .Version}}_
      {{- if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}{{- end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{- end }}
    builds:
      - windows
    files:
      - wintun.dll
    wrap_in_directory: false
    format: zip

  - id: default
    name_template: >-
      {{ .ProjectName }}_{{ .Version}}_
      {{- if eq .Os "darwin" }}macOS
      {{- else if eq .Os "linux" }}Linux
      {{- else }}{{ .Os }}{{- end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{- end }}
    builds:
      - default
    files: [only-the-binary*]
    wrap_in_directory: false
    format: tar.gz

# https://goreleaser.com/customization/changelog/
changelog:
  skip: false
  use: github
  sort: asc
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: "Dependencies"
      regexp: "^.*deps[(\\w)]*:+.*$"
      order: 30
    - title: Other
      order: 999
