# The default configuration used by the Clace server and APIs

# Service listen Config
host = "127.0.0.1"
port = 25223

# Logging related Config
log_level = "INFO"
max_backups = 10
max_size_mb = 50
console_logging = false
file_logging = true
