# The default configuration used by the Clace server and APIs

server_url = "http://127.0.0.1:25223"
admin_user = "admin"
#admin_password = 
#admin_password_bcrypt = 

# HTTP port binding related Config
[http]
host = "127.0.0.1" # bind to localhost by default for HTTP
port = 25223 # default port for HTTP

# HTTPS port binding related Config
[https]
host = "0.0.0.0" # bind to all interfaces (if port is >= 0)
port = -1 # https is disabled by default
enable_cert_lookup = true # enable looking for certificate files on disk before using Let's Encrypt
service_email = "" # email address for registering with Let's Encrypt. Set a value to enable automatic certs
use_staging = true # use Let's Encrypt staging server
cert_location = "$CL_HOME/config/certificates" # where to look for existing certificate files
storage_location = "$CL_HOME/run/certmagic" # where to cache dynamically created certificates

# Logging related Config
[logging]
level = "INFO"
max_backups = 10
max_size_mb = 50
console = false
file = true

# Metadata Storage Config
[metadata]
db_connection = "sqlite:$CL_HOME/clace.db"
auto_upgrade = true

[system]
tailwindcss_command = "npx tailwindcss"

